### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'resize'

### ISSUE THREAD

**Issue by 10Xianjin** [CrystalWlz/OMEGAS#3]
(omg) user@user-Precision-7920-Tower:~/exp/OMEGAS$ python run_gaussian.py -s data/garden/ -m output/garden
Optimizing output/garden
Output folder: output/garden [14/06 09:49:02]
Reading camera 185/185 [14/06 09:49:04]
Converting point3d.bin to .ply, will happen only the first time you open the scene. [14/06 09:49:04]
Loading Training Cameras [14/06 09:49:05]
1.18530320142334 0.8206597488990223 [14/06 09:49:05]
Traceback (most recent call last):
  File "/home/user/exp/OMEGAS/run_gaussian.py", line 294, in <module>
    train(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/user/exp/OMEGAS/run_gaussian.py", line 96, in train
    scene = Scene(dataset, gaussians)
  File "/home/user/exp/OMEGAS/gaussian_splatting/scene/__init__.py", line 73, in __init__
    self.train_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.train_cameras, resolution_scale, args)
  File "/home/user/exp/OMEGAS/gaussian_splatting/utils/camera_utils.py", line 66, in cameraList_from_camInfos
    camera_list.append(loadCam(args, id, c, resolution_scale))
  File "/home/user/exp/OMEGAS/gaussian_splatting/utils/camera_utils.py", line 46, in loadCam
    resized_objects = cam_info.objects.resize(resolution)
AttributeError: 'NoneType' object has no attribute 'resize'

**Comment by 10Xianjin** [comment]
how to solve it?
